package com.kuruhu.ai;

import org.springframework.stereotype.Service;

@Service
public class LLMService {
    public String generateResponse(String prompt, String systemInstruction) {
        return "Grounded intelligence synthesis generated by PRAMAAN AI.";
    }
}
